/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ProductDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author victor
 */
public class BuyOrDelete extends javax.swing.JFrame {
    private final ProductDAO products;
    /**
     * Creates new form BuyOrDelete
     */
    public BuyOrDelete() {
        initComponents();
        products = new ProductDAO();
        if (!products.bd.getConnection()) {
            JOptionPane.showMessageDialog(null, "Falha na conexão", "Erro 500: Banco não conectado", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        adminLabel = new javax.swing.JLabel();
        idProduto = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Stilus - Moda");
        setBackground(new java.awt.Color(240, 240, 247));
        setMaximumSize(new java.awt.Dimension(378, 300));
        setMinimumSize(new java.awt.Dimension(378, 300));
        setPreferredSize(new java.awt.Dimension(378, 300));
        getContentPane().setLayout(null);

        jLabel10.setBackground(java.awt.Color.darkGray);
        jLabel10.setFont(new java.awt.Font("Noto Sans Mono CJK JP", 1, 36)); // NOI18N
        jLabel10.setForeground(java.awt.Color.darkGray);
        jLabel10.setText("Stilus moda");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 20, 220, 40);

        jButton1.setBackground(new java.awt.Color(152, 113, 245));
        jButton1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 210, 160, 40);

        adminLabel.setBackground(java.awt.Color.darkGray);
        adminLabel.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        adminLabel.setForeground(java.awt.Color.darkGray);
        adminLabel.setText("Id do produto");
        getContentPane().add(adminLabel);
        adminLabel.setBounds(30, 80, 120, 30);
        getContentPane().add(idProduto);
        idProduto.setBounds(20, 110, 340, 35);

        jButton2.setBackground(new java.awt.Color(254, 107, 109));
        jButton2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButton2.setText("Deletar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(200, 210, 160, 40);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        if(idProduto.getText().equals("")){
            return;
        }
        confirm();
    }//GEN-LAST:event_jButton2ActionPerformed

    public void confirm(){
        int resp = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir?", "Deletar", JOptionPane.YES_NO_CANCEL_OPTION);
        if(resp==0){
            
            JOptionPane.showMessageDialog(null, products.delete(Integer.parseInt(idProduto.getText() )));
     
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminLabel;
    private javax.swing.JTextField idProduto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    // End of variables declaration//GEN-END:variables
}
