/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ProductDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author victor
 */
public class Edit extends javax.swing.JFrame {
    private final ProductDAO products;
    /**
     * Creates new form BuyOrDelete
     */
    public Edit() {
        initComponents();
        products = new ProductDAO();
        if (!products.bd.getConnection()) {
            JOptionPane.showMessageDialog(null, "Falha na conexão", "Erro 500: Banco não conectado", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        adminLabel = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        adminLabel1 = new javax.swing.JLabel();
        idProduto = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        adminLabel2 = new javax.swing.JLabel();
        category = new javax.swing.JComboBox<>();
        adminLabel3 = new javax.swing.JLabel();
        size = new javax.swing.JComboBox<>();
        adminLabel4 = new javax.swing.JLabel();
        type = new javax.swing.JTextField();
        adminLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Stilus - Moda");
        setBackground(new java.awt.Color(240, 240, 247));
        setMaximumSize(new java.awt.Dimension(800, 300));
        setMinimumSize(new java.awt.Dimension(800, 300));
        setPreferredSize(new java.awt.Dimension(800, 300));
        getContentPane().setLayout(null);

        jLabel10.setBackground(java.awt.Color.darkGray);
        jLabel10.setFont(new java.awt.Font("Noto Sans Mono CJK JP", 1, 36)); // NOI18N
        jLabel10.setForeground(java.awt.Color.darkGray);
        jLabel10.setText("Stilus moda");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(300, 0, 220, 40);

        jButton1.setBackground(new java.awt.Color(152, 113, 245));
        jButton1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(440, 210, 160, 40);

        adminLabel.setBackground(java.awt.Color.darkGray);
        adminLabel.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        adminLabel.setForeground(java.awt.Color.darkGray);
        adminLabel.setText("Novo Nome");
        getContentPane().add(adminLabel);
        adminLabel.setBounds(20, 120, 130, 30);

        price.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        getContentPane().add(price);
        price.setBounds(250, 80, 200, 35);

        jButton2.setBackground(new java.awt.Color(4, 191, 88));
        jButton2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButton2.setText("Salvar");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(620, 210, 160, 40);

        adminLabel1.setBackground(java.awt.Color.darkGray);
        adminLabel1.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        adminLabel1.setForeground(java.awt.Color.darkGray);
        adminLabel1.setText("Nova Categoria");
        getContentPane().add(adminLabel1);
        adminLabel1.setBounds(480, 120, 130, 30);

        idProduto.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        getContentPane().add(idProduto);
        idProduto.setBounds(20, 80, 200, 35);

        name.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        getContentPane().add(name);
        name.setBounds(20, 150, 200, 35);

        adminLabel2.setBackground(java.awt.Color.darkGray);
        adminLabel2.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        adminLabel2.setForeground(java.awt.Color.darkGray);
        adminLabel2.setText("Id do produto");
        getContentPane().add(adminLabel2);
        adminLabel2.setBounds(20, 50, 130, 30);

        category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Infantil", " " }));
        getContentPane().add(category);
        category.setBounds(480, 150, 300, 35);

        adminLabel3.setBackground(java.awt.Color.darkGray);
        adminLabel3.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        adminLabel3.setForeground(java.awt.Color.darkGray);
        adminLabel3.setText("Novo Tipo");
        getContentPane().add(adminLabel3);
        adminLabel3.setBounds(250, 120, 130, 30);

        size.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        size.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "P", "M", "G", "GG" }));
        getContentPane().add(size);
        size.setBounds(480, 80, 300, 35);

        adminLabel4.setBackground(java.awt.Color.darkGray);
        adminLabel4.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        adminLabel4.setForeground(java.awt.Color.darkGray);
        adminLabel4.setText("Novo Preço");
        getContentPane().add(adminLabel4);
        adminLabel4.setBounds(250, 50, 130, 30);

        type.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        getContentPane().add(type);
        type.setBounds(250, 150, 200, 35);

        adminLabel5.setBackground(java.awt.Color.darkGray);
        adminLabel5.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        adminLabel5.setForeground(java.awt.Color.darkGray);
        adminLabel5.setText("Novo Tamanho");
        getContentPane().add(adminLabel5);
        adminLabel5.setBounds(480, 50, 130, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        if(price.getText().equals("")){
            return;
        }
        confirm();
    }//GEN-LAST:event_jButton2ActionPerformed

    public void confirm(){
        int resp = JOptionPane.showConfirmDialog(null, "Deseja realmente editar?", "Editar", JOptionPane.YES_NO_CANCEL_OPTION);
        if(resp==0){
            String categoryValue = category.getSelectedItem().toString();
            String sizeValue = size.getSelectedItem().toString();
            products.product.setPreco(Integer.parseInt(price.getText()));
            products.product.setNome(name.getText());
            products.product.setTamanho(sizeValue);
            products.product.setCategoria(categoryValue);
            products.product.setTipo(type.getText());
            
            JOptionPane.showMessageDialog(null, products.update(Integer.parseInt( idProduto.getText() )));
            
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminLabel;
    private javax.swing.JLabel adminLabel1;
    private javax.swing.JLabel adminLabel2;
    private javax.swing.JLabel adminLabel3;
    private javax.swing.JLabel adminLabel4;
    private javax.swing.JLabel adminLabel5;
    private javax.swing.JComboBox<String> category;
    private javax.swing.JTextField idProduto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JTextField name;
    private javax.swing.JTextField price;
    private javax.swing.JComboBox<String> size;
    private javax.swing.JTextField type;
    // End of variables declaration//GEN-END:variables
}
