/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.UserDAO;
import java.awt.Color;
import javax.swing.JOptionPane;
import model.User;

/**
 *
 * @author victor
 */
public final class InitialPage1 extends javax.swing.JFrame {
    UserDAO users = new UserDAO();
    public String email;
    public String telefone;
    public String nome;
    public Integer userfk;
    public Boolean admin;
    
    /**
     * Creates new form Menu
     * @param user
     */
    public InitialPage1(User user) {
        initComponents();
        if (!users.bd.getConnection()) {
            JOptionPane.showMessageDialog(null, "Falha na conexão", "Erro 500: Banco não conectado", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
        users = new UserDAO();
        email = user.getEmail();
        telefone = user.getTelefone();
        admin = user.getAdmin();
        nome = user.getNome();
        userfk = user.getCodigo();
        
        
        welcome.setText("Olá, "+ nome);
        
        userCount.setText(String.valueOf(user.getRowCount()));
        if(!admin){
            adminLabel.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        welcome = new javax.swing.JLabel();
        adminLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelColor = new javax.swing.JLabel();
        labelColor1 = new javax.swing.JLabel();
        labelColor3 = new javax.swing.JSeparator();
        labelColor2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        userCount = new javax.swing.JLabel();
        labelColor4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setMinimumSize(new java.awt.Dimension(1326, 824));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(130, 87, 229));
        jPanel3.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(4, 211, 97));
        jPanel5.setLayout(null);

        jLabel10.setBackground(new java.awt.Color(240, 240, 247));
        jLabel10.setFont(new java.awt.Font("Noto Sans Mono CJK JP", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 247));
        jLabel10.setText("Stilus moda");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(90, 30, 210, 60);

        jLabel4.setBackground(new java.awt.Color(212, 194, 255));
        jLabel4.setForeground(new java.awt.Color(212, 194, 255));
        jLabel4.setText("❤");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(300, 50, 20, 30);

        jPanel3.add(jPanel5);
        jPanel5.setBounds(710, 50, 380, 120);

        jPanel6.setBackground(new java.awt.Color(152, 113, 245));
        jPanel6.setLayout(null);
        jPanel3.add(jPanel6);
        jPanel6.setBounds(770, 80, 370, 120);

        jButton1.setBackground(new java.awt.Color(152, 113, 245));
        jButton1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(240, 240, 247));
        jButton1.setText("Crie seu estilo");
        jButton1.setToolTipText("");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(620, 250, 240, 60);

        jButton2.setBackground(new java.awt.Color(4, 191, 88));
        jButton2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(240, 240, 247));
        jButton2.setText("Ver vitrine");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(990, 250, 240, 60);

        welcome.setBackground(new java.awt.Color(212, 194, 255));
        welcome.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        welcome.setForeground(new java.awt.Color(212, 194, 255));
        welcome.setText("Olá, ");
        jPanel3.add(welcome);
        welcome.setBounds(1430, 10, 150, 22);

        adminLabel.setBackground(new java.awt.Color(212, 194, 255));
        adminLabel.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        adminLabel.setForeground(new java.awt.Color(212, 194, 255));
        adminLabel.setText("Admin");
        jPanel3.add(adminLabel);
        adminLabel.setBounds(270, 0, 49, 40);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(-260, 0, 1920, 330);

        jPanel4.setBackground(new java.awt.Color(240, 240, 247));
        jPanel4.setForeground(new java.awt.Color(240, 240, 247));
        jPanel4.setToolTipText("");
        jPanel4.setLayout(null);

        jPanel2.setBackground(java.awt.Color.lightGray);

        jLabel1.setText("Stilus Moda © todos os direitos reservados.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(814, 814, 814)
                .addComponent(jLabel1)
                .addContainerGap(847, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel2);
        jPanel2.setBounds(0, 597, 1956, 73);

        labelColor.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        labelColor.setForeground(java.awt.Color.darkGray);
        labelColor.setText("Roupas do momento!");
        jPanel4.add(labelColor);
        labelColor.setBounds(820, 31, 232, 29);

        labelColor1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        labelColor1.setForeground(java.awt.Color.darkGray);
        labelColor1.setText("Personalizações únicas!");
        jPanel4.add(labelColor1);
        labelColor1.setBounds(809, 87, 262, 29);
        jPanel4.add(labelColor3);
        labelColor3.setBounds(1083, 72, 357, 22);
        jPanel4.add(labelColor2);
        labelColor2.setBounds(440, 72, 357, 22);

        jPanel1.setBackground(new java.awt.Color(4, 191, 88));
        jPanel1.setBorder(null);
        jPanel1.setForeground(new java.awt.Color(4, 191, 88));
        jPanel1.setToolTipText("Desde a criação da Stilus");

        userCount.setBackground(new java.awt.Color(240, 240, 247));
        userCount.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        userCount.setForeground(new java.awt.Color(240, 240, 247));
        userCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userCount.setText("0");
        userCount.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userCount, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(userCount, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel1);
        jPanel1.setBounds(830, 230, 230, 160);

        labelColor4.setFont(new java.awt.Font("Roboto", 2, 15)); // NOI18N
        labelColor4.setForeground(java.awt.Color.darkGray);
        labelColor4.setText("Usuários cadastrados");
        jPanel4.add(labelColor4);
        labelColor4.setBounds(830, 210, 150, 18);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(-280, 330, 1630, 670);

        jMenuBar1.setBackground(new java.awt.Color(50, 38, 77));
        jMenuBar1.setBorder(null);
        jMenuBar1.setToolTipText("Menu");
        jMenuBar1.setBorderPainted(false);
        jMenuBar1.setMinimumSize(new java.awt.Dimension(324, 42));

        jMenu1.setText("MASCULINO");
        jMenu1.setToolTipText("MASCULINO");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu1MousePressed(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("FEMININO");
        jMenu2.setToolTipText("FEMININO");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jMenu2MouseReleased(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("INFANTIL");
        jMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu3.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu3MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Config.");
        jMenu4.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jMenu4.add(jSeparator1);

        jCheckBoxMenuItem1.setText("Modo escuro");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jCheckBoxMenuItem1);

        jMenuItem9.setText("Sair");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);
        jMenuBar1.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        if(jCheckBoxMenuItem1.isSelected()){
            jPanel4.setBackground(new Color(54, 57, 63));
            labelColor1.setForeground(new Color(240,240,247));
            labelColor2.setBackground(new Color(240,240,247));
            labelColor3.setBackground(new Color(240,240,247));
            labelColor.setForeground(new Color(240,240,247));
            labelColor4.setForeground(new Color(240,240,247));
        }else{
            jPanel4.setBackground(new Color(240,240,247));
            labelColor1.setForeground(new Color(54, 57, 63));
            labelColor2.setBackground(new Color(54, 57, 63));
            labelColor3.setBackground(new Color(54, 57, 63));
            labelColor.setForeground(new Color(54, 57, 63));
            labelColor4.setForeground(new Color(54, 57, 63));
        }
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new NewProduct(userfk).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new ProductList().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
       sair();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseReleased

    }//GEN-LAST:event_jMenu2MouseReleased

    private void jMenu2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MousePressed
        new Girls().setVisible(true);
    }//GEN-LAST:event_jMenu2MousePressed

    private void jMenu1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MousePressed
        new Boys().setVisible(true);

    }//GEN-LAST:event_jMenu1MousePressed

    private void jMenu3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MousePressed
        new Kids().setVisible(true);
    }//GEN-LAST:event_jMenu3MousePressed
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(null, "Deseja sair?", "Saír", JOptionPane.YES_NO_CANCEL_OPTION);
        if(resp==0){
            dispose();
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel labelColor;
    private javax.swing.JLabel labelColor1;
    private javax.swing.JSeparator labelColor2;
    private javax.swing.JSeparator labelColor3;
    private javax.swing.JLabel labelColor4;
    private javax.swing.JLabel userCount;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
