/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.User;
import controller.UserDAO;


/**
 *
 * @author victor
 */
public class Login extends javax.swing.JFrame {
    public UserDAO users;
    /**
     * Creates new form Menu
     */
    public Login() {
        initComponents();
        users = new UserDAO();
        if (!users.bd.getConnection()) {
            JOptionPane.showMessageDialog(null, "Falha na conexão", "Erro 500: Banco não conectado", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        showPassword = new javax.swing.JCheckBox();
        register = new javax.swing.JButton();
        inputPassword = new javax.swing.JPasswordField();
        signIn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        inputEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setMinimumSize(new java.awt.Dimension(1300, 660));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(48, 48, 48));
        jLabel6.setText("Bem-vindo(a)!");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(870, 83, 210, 70);

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(0, 144, 255));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel1.setText("Stylus Moda");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel3.add(jLabel1);
        jLabel1.setBounds(190, 170, 220, 60);

        jLabel7.setBackground(new java.awt.Color(240, 240, 247));
        jLabel7.setFont(new java.awt.Font("Noto Sans Mono CJK JP", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 247));
        jLabel7.setText("Stilus");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(80, 20, 110, 60);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(140, 170, 270, 100);

        jPanel4.setBackground(new java.awt.Color(253, 161, 161));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel4.setToolTipText("");
        jPanel4.setLayout(null);
        jPanel1.add(jPanel4);
        jPanel4.setBounds(180, 200, 270, 100);

        jLabel8.setBackground(new java.awt.Color(240, 240, 247));
        jLabel8.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 247));
        jLabel8.setText("Maior loja de moda do Brasil! Stilus Moda © 2021");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 600, 350, 18);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 650, 630);

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(31, 31, 31));
        jLabel3.setText("Senha");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(170, 240, 41, 18);

        jLabel2.setBackground(new java.awt.Color(40, 40, 40));
        jLabel2.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(31, 31, 31));
        jLabel2.setText("Email");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(170, 170, 50, 18);

        showPassword.setBackground(new java.awt.Color(30, 130, 254));
        showPassword.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        showPassword.setForeground(new java.awt.Color(31, 31, 31));
        showPassword.setText("Mostrar senha");
        showPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(showPassword);
        showPassword.setBounds(170, 310, 123, 23);

        register.setBackground(new java.awt.Color(104, 146, 253));
        register.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        register.setForeground(new java.awt.Color(240, 240, 247));
        register.setText("Registre-se");
        register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        jPanel2.add(register);
        register.setBounds(170, 420, 280, 42);

        inputPassword.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        inputPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(inputPassword);
        inputPassword.setBounds(170, 260, 280, 40);

        signIn.setBackground(new java.awt.Color(104, 146, 253));
        signIn.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        signIn.setForeground(new java.awt.Color(240, 240, 247));
        signIn.setText("Entrar");
        signIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInActionPerformed(evt);
            }
        });
        jPanel2.add(signIn);
        signIn.setBounds(170, 340, 280, 42);

        jLabel4.setForeground(new java.awt.Color(31, 31, 31));
        jLabel4.setText("ou");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(300, 390, 18, 18);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(330, 400, 110, 10);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(180, 400, 110, 10);

        inputEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailActionPerformed(evt);
            }
        });
        jPanel2.add(inputEmail);
        inputEmail.setBounds(170, 190, 280, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(650, 0, 680, 630);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordActionPerformed
        if (showPassword.isSelected()) {
            inputPassword.setEchoChar((char)0);
        } else {
            inputPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_showPasswordActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed

        new register().setVisible(true);
        dispose();
    }//GEN-LAST:event_registerActionPerformed

    private void inputPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPasswordActionPerformed

    private void signInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInActionPerformed
        if(inputEmail.getText().equals("") || inputPassword.getPassword().length == 0 ){
            JOptionPane.showMessageDialog(null, "Preencha os campos", "Login não executado", JOptionPane.ERROR_MESSAGE);
            return;
        }
        users.localizarLogin(inputEmail.getText(), String.valueOf(inputPassword.getPassword()));
        users.localizarTodos();
    }//GEN-LAST:event_signInActionPerformed

    private void inputEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputEmail;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton register;
    private javax.swing.JCheckBox showPassword;
    private javax.swing.JButton signIn;
    // End of variables declaration//GEN-END:variables
}
