/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ProductDAO;
import javax.swing.JOptionPane;

/**
 * @author victor
 */
public class NewProduct extends javax.swing.JFrame {
    private final ProductDAO products;
    public Integer userfk;

    public NewProduct(int userfk) {
        initComponents();
        products = new ProductDAO();
        if (!products.bd.getConnection()) {
            JOptionPane.showMessageDialog(null, "Falha na conexão", "Erro 500: Banco não conectado", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
        this.userfk = userfk;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        buttonSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputDescription = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inputCount = new javax.swing.JTextField();
        inputName = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        selectSize = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        selectCategory = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        selectType = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novo Produto");
        setMinimumSize(new java.awt.Dimension(1326, 824));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(130, 87, 229));
        jPanel3.setLayout(null);

        jLabel10.setBackground(new java.awt.Color(240, 240, 247));
        jLabel10.setFont(new java.awt.Font("Noto Sans Mono CJK JP", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 247));
        jLabel10.setText("Stilus moda");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(1330, 70, 120, 40);

        jButton1.setBackground(new java.awt.Color(152, 113, 245));
        jButton1.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("<-------");
        jButton1.setToolTipText("Voltar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(230, 80, 110, 30);

        jLabel12.setBackground(new java.awt.Color(240, 240, 247));
        jLabel12.setFont(new java.awt.Font("Noto Sans Mono CJK JP", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(240, 240, 247));
        jLabel12.setText("Que incrível");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(600, 170, 220, 60);

        jLabel13.setBackground(new java.awt.Color(240, 240, 247));
        jLabel13.setFont(new java.awt.Font("Noto Sans Mono CJK JP", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(240, 240, 247));
        jLabel13.setText("Criar meu próprio pruduto!");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(600, 210, 480, 60);

        jLabel14.setBackground(new java.awt.Color(240, 240, 247));
        jLabel14.setFont(new java.awt.Font("Noto Sans Mono CJK JP", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(240, 240, 247));
        jLabel14.setText("Basta preencher de acordo com");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(600, 250, 480, 60);

        jLabel11.setBackground(new java.awt.Color(240, 240, 247));
        jLabel11.setFont(new java.awt.Font("Noto Sans Mono CJK JP", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 247));
        jLabel11.setText("sua necessidade.");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(600, 280, 480, 60);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(-180, -60, 1530, 330);

        jPanel1.setBackground(new java.awt.Color(240, 240, 247));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        buttonSave.setBackground(new java.awt.Color(4, 191, 88));
        buttonSave.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        buttonSave.setForeground(new java.awt.Color(240, 240, 247));
        buttonSave.setText("Salvar Cadastro");
        buttonSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });
        jPanel2.add(buttonSave);
        buttonSave.setBounds(360, 470, 160, 40);

        inputDescription.setBackground(new java.awt.Color(248, 248, 252));
        inputDescription.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        inputDescription.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        inputDescription.setForeground(java.awt.Color.darkGray);
        jScrollPane1.setViewportView(inputDescription);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 210, 240, 120);

        jLabel1.setBackground(new java.awt.Color(106, 97, 128));
        jLabel1.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(106, 97, 128));
        jLabel1.setText("Tamanho");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(270, 270, 90, 18);

        jLabel2.setBackground(new java.awt.Color(106, 97, 128));
        jLabel2.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(106, 97, 128));
        jLabel2.setText("Tipo");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(270, 190, 90, 18);

        jLabel4.setBackground(new java.awt.Color(106, 97, 128));
        jLabel4.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(106, 97, 128));
        jLabel4.setText("Descrição");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 190, 90, 18);

        jLabel5.setBackground(new java.awt.Color(106, 97, 128));
        jLabel5.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(106, 97, 128));
        jLabel5.setText("Nome");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 30, 41, 18);

        inputCount.setEditable(false);
        inputCount.setBackground(new java.awt.Color(248, 248, 252));
        inputCount.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        inputCount.setForeground(java.awt.Color.darkGray);
        inputCount.setText("0");
        inputCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCountActionPerformed(evt);
            }
        });
        jPanel2.add(inputCount);
        inputCount.setBounds(90, 130, 100, 40);

        inputName.setBackground(new java.awt.Color(248, 248, 252));
        inputName.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        inputName.setForeground(java.awt.Color.darkGray);
        jPanel2.add(inputName);
        inputName.setBounds(20, 50, 490, 40);

        jButton2.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jButton2.setText("-");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(20, 130, 60, 40);

        jButton3.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jButton3.setText("+");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(200, 130, 60, 40);

        selectSize.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        selectSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "P", "M", "G", "GG" }));
        selectSize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selectSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectSizeActionPerformed(evt);
            }
        });
        jPanel2.add(selectSize);
        selectSize.setBounds(270, 290, 240, 40);

        jLabel3.setBackground(new java.awt.Color(106, 97, 128));
        jLabel3.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(106, 97, 128));
        jLabel3.setText("Quantidade");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 110, 90, 18);

        selectCategory.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        selectCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Feminino", "Masculino", "Infantil", " " }));
        selectCategory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selectCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectCategoryActionPerformed(evt);
            }
        });
        jPanel2.add(selectCategory);
        selectCategory.setBounds(269, 130, 240, 40);

        jLabel6.setBackground(new java.awt.Color(106, 97, 128));
        jLabel6.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(106, 97, 128));
        jLabel6.setText("Categoria");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(270, 110, 90, 18);

        selectType.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        selectType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Camiseta", "Bermuda", "Vestido", "Saia", "Calça", "Pijama", "Moletom", "Social", "Acessório" }));
        selectType.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selectType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectTypeActionPerformed(evt);
            }
        });
        jPanel2.add(selectType);
        selectType.setBounds(270, 210, 240, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(450, 20, 530, 560);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-30, 250, 1360, 580);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        cadastro();
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void inputCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCountActionPerformed

    private void selectSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectSizeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int current = Integer.parseInt(inputCount.getText().toString().trim());
        
        current = current + 1;
        inputCount.setText(String.valueOf(current));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int current = Integer.parseInt(inputCount.getText().toString().trim());
        if(Integer.parseInt(inputCount.getText().toString().trim())> 0){
            current = current - 1;
        }
        inputCount.setText(String.valueOf(current));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void selectCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectCategoryActionPerformed

    private void selectTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectTypeActionPerformed

        public void cadastro() {
            if (inputName.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "O nome nao pode ser vazio!", "Produto não foi cadastrado", JOptionPane.ERROR_MESSAGE);
                inputName.requestFocus();
                return;
            }
            if (inputCount.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Quantidade não pode ser vazia!", "Produto não foi cadastrado", JOptionPane.ERROR_MESSAGE);
                inputCount.requestFocus();
                return;
            }
            if(Integer.parseInt(inputCount.getText()) <= 0){
                JOptionPane.showMessageDialog(null, "Quantidade não pode ser 0!", "Produto não foi cadastrado", JOptionPane.ERROR_MESSAGE);
                inputCount.requestFocus();
                return;
            }
            if (inputDescription.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "A descrição nao pode ser vazia!", "Produto não foi cadastrado", JOptionPane.ERROR_MESSAGE);
                inputDescription.requestFocus();
                return;
            }

            
            String category = selectCategory.getSelectedItem().toString();
            String type = selectType.getSelectedItem().toString();
            String size = selectSize.getSelectedItem().toString();
            
            products.product.setNome(inputName.getText());
            products.product.setCategoria(category);
            products.product.setTipo(type);
            products.product.setQuantidade(Integer.parseInt(inputCount.getText()));
            products.product.setDescricao(inputDescription.getText());
            products.product.setTamanho(size);
            products.product.setCodigo(userfk);
            products.product.setPreco(100);
            
            JOptionPane.showMessageDialog(null, products.post());
            limpar();
        }
        public void limpar(){
            inputName.setText("");
            inputDescription.setText("");
        
        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSave;
    private javax.swing.JTextField inputCount;
    private javax.swing.JTextPane inputDescription;
    private javax.swing.JTextField inputName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> selectCategory;
    private javax.swing.JComboBox<String> selectSize;
    private javax.swing.JComboBox<String> selectType;
    // End of variables declaration//GEN-END:variables
}
